name: my-app
on: [push]
jobs:
  hello:
    name: hello
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "hello"
  world:
    name: world
    runs-on: ubuntu-latest
    steps:
      - name: print world
        run: echo "world"
