name: my-app
on: [push]
jobs:
  hello:
    name: hello
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: |
          hello=hello
          echo "$hello"
  world:
    name: world
    runs-on: ubuntu-latest
    steps:
      - name: print world
        run: |
          world=world
          echo "$world"
  hello-world:
    name: hello-world
    runs-on: ubuntu-latest
    steps:
      - name: print world
        run: echo "$hello$world"
